# Generated by Django 5.0.6 on 2024-07-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0002_streamplatform_watchlist_delete_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="description",
            new_name="storyline",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="updated",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="watchlist_app.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
