# Generated by Django 5.0.6 on 2024-07-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0005_review_review_user_alter_review_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="number_rating",
            field=models.FloatField(default=0),
        ),
    ]
